### ISSUE TITLE
Move the server application into it's own account.

### ISSUE THREAD

**Issue by peristeri** [neuropoly/sct_testing_management#2]

**Comment by peristeri** [comment]
The docker setup is now under the controller of a ansible script. The script will be saved in a private repository.

**Comment by jcohenadad** [comment]
reopening it because documentation is missing: which username, etc. info needs to be sent to me.

**Comment by peristeri** [comment]
The web server is running in a docker container supervised by a root daemon. There will be documentation on how to deploy in the README file. Will require to setup the keys of those administrating tristano.

**Comment by peristeri** [comment]
Delivered the ansible script with the documentation.
