### ISSUE TITLE
Error: "The state of the file: File not available"

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/sct_testing_management#21]
![screen shot 2018-04-02 at 16 32 53](https://user-images.githubusercontent.com/2482071/38187646-843d8488-3693-11e8-996e-d40bdef51fe9.png)

The file is available:
~~~
julien-macbook:/Volumes/sct_testing/large/unf_sct_025/t2 $ ll
total 18320
drwx------  1 julien  staff      264 15 Mar 07:27 .
drwx------  1 julien  staff      264 15 Mar 07:26 ..
-rwx------@ 1 julien  staff  9378760 15 Mar 07:12 t2.nii.gz
~~~

**Comment by peristeri** [comment]
The path prefix was wrong. It is solved by fixing the environment variables.
