### ISSUE TITLE
Installation procedure

### ISSUE THREAD

**Issue by perone** [neuropoly/sct_testing_management#26]
Hi, I'm trying to install it locally. I installed using the `local.txt` requirements:

    pip install -r requirements/local.txt

And then I called:

    python manage.py check_filenames

and I got this error:

```
  File "/Users/chper/Desktop/sct_web/sct_testing_management/sct_annotation/taskapp/celery.py", line 3, in <module>
    from celery import Celery
ImportError: cannot import name Celery
```
I think it would be nice to have an installation procedure that we can reproduce locally. Another question, am I supposed to use Python 2 or 3 ?

**Comment by peristeri** [comment]
The python version tested is 3.6. Will look into the missing import.

**Comment by peristeri** [comment]
Can you run `pip freeze` to see if celery is installed?

**Comment by perone** [comment]
In `pip freeze` I have `celery==4.1.0`. However, it might be the Python version issue because I used Python 2.x. It would be nice to add that to the docs (to state that it was written/tested in Python 3) because the installation for Python 2 works fine.
