### ISSUE TITLE
Add center dropdown list for acquisition and contrast

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/sct_testing_management#30]
Add option of dropdown list with predefined centres (e.g. paris, unf, twh, etc.) when adding new acquisition in the DB

**Comment by jcohenadad** [comment]
also do dropdown for:
- contrast
- study

**Comment by alexfoias** [comment]
For contrast we have a big variability (**t1_*** , **t2_*** ,  **t2s_***) because of the **mgh-3t connectome** scans. Here are all contrasts listed in DB:

dmri
dwi
fmri
mt
t1
t1_ax_fl_mtv_10
t1_ax_fl_mtv_10_0017
t1_ax_fl_mtv_20
t1_ax_fl_mtv_20_0016
t1_ax_fl_mtv_30
t2
t2_hypersignal
t2s
t2_sag_tse
t2s_ax_fl_mtv_04_0018
t2s_ax_fl_mtv_4

Should we modify them and only keep a short list ? Here is an example:

dmri
dwi
fmri
mt
t1
t2
t2s

For study & center, are we going with a dropdown menu & the possibility of adding the field is it's not in the list ?

**Comment by jcohenadad** [comment]
@alexfoias i would go with:
~~~
dwi
fmri
t1
t2
t2s
~~~
note that dwi and fmri could, in principle, be 3D or 4D, so it would be great to add a field that specifies if the data is 3D or 4D (could you open an issue-- not that this could be found automatically from the image header-- as done for the orientation).

for study/center: yes, dropdown menu with possibility to add. BTW: it would be important to get have somewhere the relation between the short and long center definition (e.g. mgh = massachusetts general hospital, boston, usa). Creating a dictionary would be a good approach. Could you pls open an issue? thx!

**Comment by alexfoias** [comment]
I would like to solve this issue step by step based on the individual issues:
- [Contrast dropdown list](https://github.com/neuropoly/sct_testing_management/issues/55)
- [Center dropdown list](https://github.com/neuropoly/sct_testing_management/issues/58)
- [Study dropdown list](https://github.com/neuropoly/sct_testing_management/issues/62)
- [fMRI data dimension](https://github.com/neuropoly/sct_testing_management/issues/59)

**Comment by alexfoias** [comment]
This issue is very old. We have abandoned this system. We can close the issue.
