### ISSUE TITLE
Warning: .nii files wrongly named with extension nii.gz

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/sct_testing_management#45]
List of files:

- [x] ucsf_2017-talbott_1001/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1002/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1003/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1004/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1005/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1006/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1007/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1008/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1009/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1011/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_10112/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1013/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1014/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1015/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1016/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1017/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1018/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1019/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1020/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1021/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1022/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1023/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1024/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1025/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1026/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1027/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1028/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1029/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1030/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1031/t2_sag/t2_sag.nii
- [x] ucsf_2017-talbott_1032/t2_sag/t2_sag.nii

TODO:
- go to each folder, change extension .nii.gz -> .nii
- compress:
~~~
for i in `ls *.nii`; do fslchfiletype NIFTI_GZ $i; done
~~~

**Comment by alexfoias** [comment]
I identified the following files with the wrong extensions:

/Volumes/sct_testing/large/amu_2017-virginie_BZ/t2/t2.nii
/Volumes/sct_testing/large/sherbrooke_biospective_100-005-s1/t2/labels.nii
/Volumes/sct_testing/large/sherbrooke_biospective_100-006-s1/t2/labels.nii
/Volumes/sct_testing/large/sherbrooke_biospective_100-009-s1/t2/labels.nii
/Volumes/sct_testing/large/sherbrooke_biospective_100-010-s1/t2/labels.nii
/Volumes/sct_testing/large/sherbrooke_biospective_100-012-s1/t2/labels.nii
/Volumes/sct_testing/large/ucsf_2017-talbott_1010/t2_sag/t2_sag.nii
/Volumes/sct_testing/large/unf_biospective_200-004-s1/t2/labels.nii
/Volumes/sct_testing/large/unf_biospective_200-005-s1/t2/labels.nii
/Volumes/sct_testing/large/unf_biospective_200-006-s1/t2/labels.nii
/Volumes/sct_testing/large/unf_biospective_200-009-s1/t2/labels.nii
/Volumes/sct_testing/large/unf_biospective_200-010-s1/t2/labels.nii
/Volumes/sct_testing/large/unf_biospective_200-011-s1/t2/labels.nii
/Volumes/sct_testing/large/unf_biospective_200-012-s1/t2/labels.nii
/Volumes/sct_testing/large/unf_biospective_200-013-s1/t2/labels.nii
/Volumes/sct_testing/large/unf_biospective_200-015-s1/t2/labels.nii
/Volumes/sct_testing/large/unf_biospective_200-016-s1/t2/labels.nii
/Volumes/sct_testing/large/unf_biospective_200-017-s1/t2/labels.nii
/Volumes/sct_testing/large/unf_biospective_200-018-s1/t2/labels.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_01/t1/t1_fat.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_01/t1/t1_inn.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_01/t1/t1_opp.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_01/t1/t1_wat.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_02/t1/t1_fat.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_02/t1/t1_inn.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_02/t1/t1_opp.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_02/t1/t1_wat.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_03/t1/t1_fat.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_03/t1/t1_inn.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_03/t1/t1_opp.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_03/t1/t1_seg_manual.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_03/t1/t1_wat.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_04/t1/t1_fat.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_04/t1/t1_inn.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_04/t1/t1_opp.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_04/t1/t1_wat.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_04/t1/t1_wat_seg.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_05/t1/t1_fat.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_05/t1/t1_inn.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_05/t1/t1_opp.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_05/t1/t1_wat.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_06/t1/t1_fat.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_06/t1/t1_inn.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_06/t1/t1_opp.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_06/t1/t1_wat.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_07/t1/t1_fat.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_07/t1/t1_inn.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_07/t1/t1_opp.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_07/t1/t1_wat.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_08/t1/t1_fat.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_08/t1/t1_inn.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_08/t1/t1_opp.nii
/Volumes/sct_testing/large/unknown_ivdm3seg_08/t1/t1_wat.nii

**Comment by alexfoias** [comment]
@jcohenadad Just to make sure before changing the files, we want .nii -> .nii.gz or .nii.gz -> .nii (as you mentioned in the initial comment to the issue) ? thanks

**Comment by jcohenadad** [comment]
@alexfoias, please **do not** use the list that you made, but rather address the files that @hadihammoud will list as a replacement for my XXX [here](https://github.com/neuropoly/sct_testing_management/issues/45#issue-342865616). What happens is that those files are nii files, but they are wrongly named with extension .nii.gz. So what we want to do with these files is:
- rename them with extension .nii
- and then compress:
~~~
for i in `ls *.nii`; do fslchfiletype NIFTI_GZ $i; done
~~~

**Comment by alexfoias** [comment]
@jcohenadad I compressed the data using FSL. In addition, I tested the data using FSLeyes, without any erroré
