### ISSUE TITLE
Check primary & verified  fields under users webpage

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/sct_testing_management#51]

**Comment by alexfoias** [comment]
@jcohenadad I did some research concerning the primary & verified fields on : [link](http://tristano.neuro.polymtl.ca/admin/account/emailaddress/). These fields are generated when someone signs up using the [link](http://tristano.neuro.polymtl.ca/accounts/signup/?next=%2F). For the moment ACCOUNT_EMAIL_VERIFICATION = 'none', that's why the users are not verified.

**Comment by jcohenadad** [comment]
how come some users are verified then? (green check)

also, what defines "PRIMARY"?

**Comment by alexfoias** [comment]
Some users are are verified because the previous deploy of the app had the email verification mandatory at the moment of creation of the username. On the other hand, for CJ you added him manually to the database and changed the status to verified.

PRIMARY is the email associated to the username (either created via the sign up form or from admin interface).

**Comment by jcohenadad** [comment]
what should be the standard procedure to add people? is there a doc somewhere? (if not can you pls add)? thx

**Comment by alexfoias** [comment]
This issue is very old. We have abandoned this system. We can close the issue.
