### ISSUE TITLE
in image edit, show "acquisition" field with underscore separator

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/sct_testing_management#54]
instead of having this in the dropdown menu:
![screen shot 2018-08-06 at 11 19 01](https://user-images.githubusercontent.com/2482071/43725473-9eea8ef4-996a-11e8-8359-a1b069e9afef.png)

replace with: `sapienza_sct-users_mauro-01`, which is more consistent with the physical folder name (hence more intuitive)

**Comment by alexfoias** [comment]
This issue is very old. We have abandoned this system. We can close the issue.
