### ISSUE TITLE
the contrast dropdown in Image section is not exhaustive

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/sct_testing_management#55]
see below:
![screen shot 2018-08-06 at 11 20 47](https://user-images.githubusercontent.com/2482071/43725562-dcb2d55c-996a-11e8-8d15-e47099d548c0.png)

more contrasts should appear (t1, t2, etc.)

**Comment by alexfoias** [comment]
This issue is very old. We have abandoned this system. We can close the issue.
