### ISSUE TITLE
add a regular check for filenames

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/sct_testing_management#8]
e.g. check if files exist.
this check could be run on a nightly basis

**Comment by peristeri** [comment]
What is the required results for (images / labeled images) with missing files?

**Comment by jcohenadad** [comment]
i'm not sure, this should be discussed at the next SCT meeting. A few ideas with pros/cons:
- sending email to the team with a list of missing labels. Cons: too overwhelming because labels will likely always be missing for the next few months. 
- output a txt file (or send an email to the list) whenever asked for. Which means not running the test every night.

**Comment by peristeri** [comment]
An other option is to have a status field in the database with the options:

- Available
- Missing
- Corrupted

**Comment by jcohenadad** [comment]
what would be an example of corrupted?

**Comment by peristeri** [comment]
I found files that nibabel throws an exception when loading the file `nibabel.load(nii_file)`. I found several files.

**Comment by jcohenadad** [comment]
can you please list one example?

**Comment by peristeri** [comment]
An example of a corrupt file is /Volumes/sct_testing/large/ucsf_2017-talbott_1001/t2_sag/t2_sag.nii.gz It is all t2s images from session 1001 to 1032

**Comment by jcohenadad** [comment]
I can reproduce the issue. It was probably related to a wrong file naming extension, which was manually changed from `nii` to `nii.gz`. 
Simply renaming the file from `t2_sag.nii.gz` to `t2_sag.nii` should solve the issue.
